export const postSagaActions = {
  FETCH_DATA_POSTS: "FETCH_DATA_POSTS",
  FETCH_DATA_POSTS_LOADING: "FETCH_DATA_POSTS_LOADING",
  FETCH_DATA_POSTS_SUCCESS: "FETCH_DATA_POSTS_SUCCESS",
  FETCH_DATA_POSTS_ERROR: "FETCH_DATA_POSTS_ERROR",
};
