#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 testing and building your project before committing'

# Check ESLint Standards
 yarn run lint
 (
         echo '😤🏀👋😤  ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. 😤🏀👋😤 '
         false;
 )

# run test
# yarn run test
# (
#     echo '🤡😂❌🤡 Tests Failed. 🤡😂❌🤡'
#     false;
# )


# If everything passes... Now we can commit
# echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

# yarn run build-all ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             Next build failed: View the errors above to see why.
#     '
#     false;
# )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
